// Stub class generated by rmic, do not edit.

// This is the stub generated using the following command "rmic -keep gmit.DictionaryRMIObj"

package gmit;

public final class DictionaryRMIObj_Stub
    extends java.rmi.server.RemoteStub
    implements gmit.DictionaryInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_findWord_0;
    
    static {
	try {
	    $method_findWord_0 = gmit.DictionaryInterface.class.getMethod("findWord", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public DictionaryRMIObj_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of findWord(String)
    public java.lang.String findWord(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_findWord_0, new java.lang.Object[] {$param_String_1}, 7342129527800819057L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
